version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:5c6f1132190256d1ee63afc3bb383c890e8cb9f547bb1f8f15fecaa2a78e7de0
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:0e06c2deca31072cedfbdd53e4f8988713ecaa5ef45c2a31ab77edb2cc50fdc0
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8081:8081'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8081
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:61b6cc81ecc3f94f614dca6bfdc5262d15a6618f7aabfbfc6f9f05c935ee753c
    platform: linux/amd64
    env_file:
      - .docker/local.env
    working_dir: /app
    ports:
      - '4025:4025'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm ci && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
      - snowplow

  snowplow:
    image: pocket/snowplow-micro:latest
    platform: linux/amd64
    ports:
      - '9090:9090'
