version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:372af24c361a5466db159b7a2b9726762473b9a8f097fe66d3df43ba0df51743
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:c3b9fe5079928acd642ed21633d94babc6a135164eea7b70b00f647f28c99c1b
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8081:8081'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8081
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:4c1e36b70fc464b74fb6824f15416f851982d2708412d0076786434b075d9a49
    platform: linux/amd64
    env_file:
      - .docker/local.env
    working_dir: /app
    ports:
      - '4025:4025'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm ci && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
      - snowplow

  snowplow:
    image: pocket/snowplow-micro:latest
    platform: linux/amd64
    ports:
      - '9090:9090'
