version: '3.1'
services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./.docker/local.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack
    env_file:
      - .docker/local.env
    ports:
      - '4567:4567'
      - '8081:8081'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8081
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16
    env_file:
      - .docker/local.env
    working_dir: /app
    ports:
      - '4025:4025'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm ci && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
