version: '3.1'
services:
  mysql:
    image: mysql:5.7@sha256:bbe0e2b0a33ef5c3a983e490dcb3c1a42d623db1d5679e82f65cce3f32c8f254
    platform: linux/amd64
    env_file:
      - ./.docker/local.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  localstack:
    image: localstack/localstack@sha256:7f73f166e842f8480673f3c113b14350fa9db72960335e27e3be007f100272c4
    platform: linux/amd64
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8081:8081'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8081
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  app:
    image: node:16@sha256:2e1b4542d4a06e0e0442dc38af1f4828760aecc9db2b95e7df87f573640d98cd
    platform: linux/amd64
    env_file:
      - .docker/local.env
    working_dir: /app
    ports:
      - '4025:4025'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm ci && npm run start:dev'"
    depends_on:
      - mysql
      - localstack
      - snowplow

  snowplow:
    image: pocket/snowplow-micro:latest
    platform: linux/amd64
    ports:
      - '9090:9090'
