version: '3.1'
services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./.docker/local.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  app:
    image: node:15
    env_file:
      - .docker/local.env
    working_dir: /app
    ports:
      - '4025:4025'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=local
    command: "bash -c 'cd /app && npm ci && npm run start:dev'"
    depends_on:
      - mysql
