name: Verify Snowplow Schema Dependencies

####################################
# Start the job on all PRs to main #
####################################
on:
  pull_request:
    branches:
      - main

jobs:
  data-structures-check:
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ##########################
      # Run the Snowplow check #
      ##########################
      - name: Run Snowplow's Data Structures CI
        uses: snowplow-product/msc-schema-ci-action/check@v1
        with:
          organization-id: ${{ secrets.SNOWPLOW_ORG_ID }}
          api-key: ${{ secrets.SNOWPLOW_API_KEY }}
          manifest-path: '.github/workflows/snowplow/schemas.json'
          environment: PROD
