#####################################
# For documentation, see https://docs.snowplowanalytics.com/docs/managing-data-quality/testing-and-qa-workflows/using-the-data-structures-ci-tool-for-data-quality/
####################################
name: Verify Snowplow Schema Dependencies

####################################
# Start the job on all PRs to main #
####################################
on:
  pull_request_target:
    branches:
      - main

jobs:
  data-structures-check:
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      ##########################
      # Run the Snowplow check #
      ##########################
      - name: Run Snowplow's Data Structures CI
        uses: snowplow-product/msc-schema-ci-action/check@afb795c9a9ca1a162a8a2dbd49dbe09f8db3c0f0 # tag=v1
        with:
          organization-id: ${{ secrets.SNOWPLOW_ORG_ID }}
          api-key: ${{ secrets.SNOWPLOW_GITHUB_CHECKS }}
          manifest-path: '.github/workflows/snowplow/schemas.json'
          # Note options here are DEV or PROD. These are magic Snowplow words
          # and they don't correspond to traditional Node env values such as
          # 'production'
          environment: PROD
